---
collections:
  - name: community.general
    version: 12.3.0
  - name: community.sops
    version: 2.2.7
  - name: community.mysql
    version: 4.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.docker
    version: 5.0.6
  - name: ansible.posix
    version: 2.1.0
  - name: community.routeros
    version: 3.16.0
